package com.siagajiwa.siagajiwa.data.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class User(
    @SerialName("id")
    val id: String = "",

    @SerialName("email")
    val email: String = "",

    @SerialName("full_name")
    val fullName: String = "",

    @SerialName("avatar_url")
    val avatarUrl: String? = null,

    @SerialName("stress_level")
    val stressLevel: String? = null,

    @SerialName("stress_score")
    val stressScore: Int? = null,

    @SerialName("knowledge_score")
    val knowledgeScore: Int? = null,

    @SerialName("user_id")
    val userID: String = "",

    @SerialName("knowledge_percentage")
    val knowledgePercentage: Int? = null,

    @SerialName("created_at")
    val createdAt: String? = null,

    @SerialName("updated_at")
    val updatedAt: String? = null
)

@Serializable
data class UserProfile(
    @SerialName("id")
    val id: String,

    @SerialName("email")
    val email: String,

    @SerialName("full_name")
    val fullName: String,

    @SerialName("avatar_url")
    val avatarUrl: String? = null
)

@Serializable
data class StressData(
    @SerialName("id")
    val id: String? = null,  // UUID generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("stress_level")
    val stressLevel: String,

    @SerialName("stress_score")
    val stressScore: Int,

    @SerialName("test_date")
    val testDate: String? = null,  // Auto-generated by Supabase if not provided

    @SerialName("created_at")
    val createdAt: String? = null  // Auto-generated by Supabase
)

@Serializable
data class QuizData(
    @SerialName("id")
    val id: String? = null,  // UUID generated by Supabase

    @SerialName("user_id")
    val userId: String,

    @SerialName("quiz_score")
    val quizScore: Int,

    @SerialName("total_questions")
    val totalQuestions: Int = 24,  // Default value as per schema

    @SerialName("percentage")
    val percentage: Int,

    @SerialName("quiz_date")
    val quizDate: String? = null,  // Auto-generated by Supabase if not provided

    @SerialName("created_at")
    val createdAt: String? = null  // Auto-generated by Supabase
)
